### PR TITLE
Replace javadsl-server with javadsl-client artifact for the front-end…

### PR DESCRIPTION
**Pull request by igorbolic**
When running `mvn lagom:runAll`, **front-end** module startup will fail with the following error: 

> com.google.inject.ProvisionException: Unable to provision, see the following errors:
> 
> 1) No implementation for com.lightbend.lagom.javadsl.server.LagomServiceRouter was bound.
>   while locating com.lightbend.lagom.javadsl.server.LagomServiceRouter
>   while locating play.api.inject.RoutesProvider
>   while locating play.api.routing.Router
>     for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:217)
>   while locating play.api.http.JavaCompatibleHttpRequestHandler
>   while locating play.api.http.HttpRequestHandler
>     for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
>   at play.api.DefaultApplication.class(Application.scala:235)
>   while locating play.api.DefaultApplication
>   while locating play.api.Application

Replacing the **lagom-javadsl-server** with **lagom-javadsl-client** artifact, will avoid initialization error for the `LagomServiceRouter`.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @igorbolic,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ignasi35** [comment]
Hi @igorbolic [this line](https://github.com/lagom/lagom-java-maven-chirper-example/pull/12/files#diff-a19e27ede91d7f2db76a4cf0fbec8c20R58) was added in #12. I wonder if your change will break the deployment. 🤔

**Comment by igorbolic** [comment]
I don't believe this change will break something. The PR was based on the master branch, and as long as there are no conflicts with merge, it should be fine.

**Comment by ignasi35** [comment]
@igorbolic my concern was that the build currently doesn't exercise a deployment. It compiles the code and runs a few tests but there's no automated process to deploy and run a smoke test.

I've given it some more thought and I agree that the suggested change is correct.

**Comment by ignasi35** [comment]
@igorbolic my concern was that the build currently doesn't exercise a deployment. It compiles the code and runs a few tests but there's no automated process to deploy and run a smoke test.

I've given it some more thought and I agree that the suggested change is correct.

**Comment by ignasi35** [comment]
@igorbolic my concern was that the build currently doesn't exercise a deployment. It compiles the code and runs a few tests but there's no automated process to deploy and run a smoke test.

I've given it some more thought and I agree that the suggested change is correct.

Thanks @igorbolic ! :-)

**Comment by ignasi35** [comment]
@igorbolic my concern was that the build currently doesn't exercise a deployment. It compiles the code and runs a few tests but there's no automated process to deploy and run a smoke test.

I've given it some more thought and I agree that the suggested change is correct.

Thanks @igorbolic ! :-)

**Pull request merged**
