### PR TITLE
[WIP] Fork Chirper into Maven only build

### PR DESCRIPTION
**Pull request by longshorej**
The Maven counterpart of https://github.com/lagom/lagom-java-sbt-chirper-example/pull/1

*WIP: Needs deployment recipes added back*

### CODE REVIEW

**Review by octonato — APPROVED** [review]

**Comment by octonato** [comment]
Some extra thoughts...
Do we have any plans to have a common core to avoid code duplication and extra maintenance?

Alternatively, we could have a good old rsync script. WDYT?

**Comment by longshorej** [comment]
It's a good consideration. I think we could all setup our forks with multiple remotes and `git cherry-pick <id>` into the relevant branch.

I'm not sure there's enough activity to warrant anything more complex than that imo: https://github.com/lagom/lagom-java-maven-chirper-example/commits/master

**Comment by octonato** [comment]
Sure, cherrypicking will work as long as we never mix build changes and project change on the same commit. That can especially happen when adding new dependencies and related new code.

Let's first try with cherrypicking and some diligence. As you said, there isn't much activity on the core.

**Comment by TimMoore** [comment]
Closing and reopening just to trigger PR validation...

**Review by TimMoore — COMMENTED** [review]
Since there is no Kuburnetes tooling for Maven at the moment, should we keep the existing instructions, POM configuration for Docker builds, and k8s resource files in this repo?

**Comment by longshorej** [comment]
> Since there is no Kuburnetes tooling for Maven at the moment, should we keep the existing instructions, POM configuration for Docker builds, and k8s resource files in this repo?

Yeah, seems like that would be useful. I'll move this to WIP until tomorrow.

**Pull request closed without merging**
